apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homebridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
  {{- if .Values.keel.enabled }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | quote }}
    keel.sh/trigger: {{ .Values.keel.trigger | quote }}
    keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
    keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
  {{- end }}
spec:
  serviceName: {{ include "homebridge.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "homebridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homebridge.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.keel.enabled }}
      annotations:
        keel.sh/policy: {{ .Values.keel.policy | quote }}
        keel.sh/trigger: {{ .Values.keel.trigger | quote }}
        keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
        keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homebridge.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .containerPort }}
              {{- if .protocol }}
              protocol: {{ .protocol }}
              {{- end }}
              name: {{ .name }}
            {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /homebridge
            {{- if .Values.bluetooth.enabled }}
            - name: bluetooth
              mountPath: {{ .Values.bluetooth.hostPath }}
            {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-data" (include "homebridge.fullname" .)) }}
        {{- if .Values.bluetooth.enabled }}
        - name: bluetooth
          hostPath:
            path: {{ .Values.bluetooth.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
