{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homebridge.fullname" . }}-data
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClass }}
  local:
    path: {{ .Values.persistence.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.nodeAffinityHost }}
{{- end }}
