{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ping.fullname" . }}
  labels:
    {{- include "ping.labels" . | nindent 4 }}
data:
  blackbox.yml: |
    {{- .Values.config.blackboxYml | nindent 4 }}
{{- end }}
