apiVersion: v2
name: listmonk
description: Self-hosted newsletter and mailing list manager
type: application
version: 0.1.0
appVersion: "4.1.0"
icon: https://cdn.lbenicio.dev/logos/listmonk.png
keywords:
  - newsletter
  - mailing-list
  - email
  - listmonk
home: https://listmonk.app
sources:
  - https://github.com/listmonk/listmonk
maintainers:
  - name: lbenicio
