{{- if .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
stringData:
  db-config.json: |
    {
      "type": {{ .Values.externalDatabase.type | quote }},
      "hostname": {{ .Values.externalDatabase.hostname | quote }},
      "port": {{ .Values.externalDatabase.port }},
      "username": {{ .Values.externalDatabase.username | quote }},
      "password": {{ .Values.externalDatabase.password | quote }},
      "dbName": {{ .Values.externalDatabase.dbName | quote }}
    }
{{- end }}
