apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listmonk.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
  {{- if .Values.keel.enabled }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | quote }}
    keel.sh/trigger: {{ .Values.keel.trigger | quote }}
    keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
    keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "listmonk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "listmonk.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.keel.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.keel.enabled }}
        keel.sh/policy: {{ .Values.keel.policy | quote }}
        keel.sh/trigger: {{ .Values.keel.trigger | quote }}
        keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
        keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /listmonk/config.toml
              subPath: config.toml
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "listmonk.fullname" . }}-config
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
