{{- if .Values.config.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-pilot.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-pilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.config.oidc.clientId | quote }}
  clientSecret: {{ .Values.config.oidc.clientSecret | quote }}
{{- end }}
---
{{- if .Values.config.k8sToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-pilot.fullname" . }}-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-pilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.config.k8sToken | quote }}
{{- end }}
