{{- if .Values.config.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-pilot.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-pilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.config.oidc.clientId | quote }}
  clientSecret: {{ .Values.config.oidc.clientSecret | quote }}
{{- end }}
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-pilot.fullname" . }}-sa-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-pilot.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "helm-pilot.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
