{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stremio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stremio.labels" . | nindent 4 }}
{{- end }}
