apiVersion: apps/v1
kind: {{ .Values.controller.type }}
metadata:
  name: {{ include "prowlarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.keel.enabled }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | quote }}
    keel.sh/trigger: {{ .Values.keel.trigger | quote }}
    keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
    keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
  {{- end }}
spec:
  {{- if eq .Values.controller.type "Deployment" }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  {{- end }}
  {{- if eq .Values.controller.type "StatefulSet" }}
  serviceName: {{ include "prowlarr.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prowlarr.selectorLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "prowlarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.keel.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.keel.enabled }}
        keel.sh/policy: {{ .Values.keel.policy | quote }}
        keel.sh/trigger: {{ .Values.keel.trigger | quote }}
        keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
        keel.sh/match-tag: {{ .Values.keel.matchTag | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- with .Values.env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.persistence.config }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- range .Values.persistence.config }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName | default (printf "%s-%s" (include "prowlarr.fullname" $) .name) }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
