apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedtest.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName | default "http" }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
  selector:
    {{- include "speedtest.selectorLabels" . | nindent 4 }}
