{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searxng.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
data:
  SEARXNG_SECRET: {{ include "searxng.secretValue" . | b64enc | quote }}
{{- end }}
